### Sign Up request
POST http://localhost:8080/signup

{
  "username": "Josh",
  "password": "pass",
  "email": "narchos@gmail.com"
}

### Signin request with correct password

POST http://localhost:8080/signin

{
  "username": "narchos@gmail.com",
  "password": "pass"
}

### Signin request with incorrect password

POST http://localhost:8080/signin

{
  "username": "Narcos",
  "password": "incorrect"
}